env:
  global:
    # reviewdog
    - secure: "CNZXODvXHMB0z6Z+Jd8MjzP+RYgRzkykRNpZdCDCo6AC57BpV5U20Mn9o2MGhTA9lMgtyNXXEaQxeIGZMFp3iB2UHiPif1UD4C0uDttytTuCcmHMlBIVP8GiNcAexi1Zv2SchM1k8z3tw5zDhkYMwjs/4ZsGVXHa1ip/UzpZaJBPl9D64wedJxZGBjS/Kn9IZTrMkL2otr8rKk0ZFMtwDkHKdjfikZ+PAlkYpX2a2Dp69HTLbEtx+ugocNj02hzgVYNpFXA1K0CulyCYJq7oqdx0UFbtKEd3urYFWfmxEZSg6SoHcIujC+/BKfZELFyA3uomp+cLpGaRlEp/iAlj/ixTo4iFtu6XdDOim4J9ZVtNSg6DdDstL9uhxCu+vca/ntViGfyw6CF0hKcHTZvlH2awiV1njmHFdRvoaMy/1fdw1JAV9O7ylU3bV5GrF6fMQ1CpweYCnF3IMpvvwdeUnGR6NPvqjybcnyXoTXZ139PxfWzbUzSG8KbOvzt1aVhWF5184b8fqhN3768Y1stke+FjFpARqlPVsfzS7fnn5kx8zZ5nfmwZjnL/WFob24mvm+/9e7IsfWmeEQdFspD+spBE4WOta7tegqh5ANNfM2owd9evtH5kqlCLeAVD3LMs69ZQW45KS0rDJpY8+ffMWRJRmoM/pweW3CmbHPeb468="
    # https://codecov.io/gh/CovenantSQL/CovenantSQL
    - secure: "iJVHTJ8NNzb3UKgh8VRXZg+XVXxcnH10dPDyg44Osp67bkwB46nIDAgDvPRZCX4Kr2Q7FCip1DT1DzkcxCBqCD7XgSsvtoP05kckWZf5dUp2qdaaBgFBR5F2ijhTgpqSG2/MZyY/9DRZhfd/DTywo4K4cGRGpjUYm7BSmR/5ou1Dk6CksoPFMwkE0zHVdRBkRoMaqqVGl9uxFyU6ssZ9IFsLbbSiJ+/iFZDbfBMuzhpxziJ4Oli1LrveEMCCnwKFgVURD3bVUtHrpdQ1RNJQzjkM8tvtilrh3Sf5X9+sJ8K+N1NnzDJiPnEZfkd69vDSh5gEivgIg3j9zIgQGfreDoKCOTfEgzGxRaPusokLQUyDGcU0ZMtLV3mzikeWJ1nUv7jOR8RF97KoJL/ZEgK5Owh5w3WhA+EcvuWC5gggi5Lx2mf7AK6zbm5JiOomBZLINKnygT+tHOKbuglDgP2UL7OBDE3xCI+WT4q3Zz6VKuNdwEFv81Qg925QFr9ifZlCPSzaNHkepEGji++3yFaEPTEtS3TzM+DTqOefU/I1q4IFvgHRMh4M7AbYQPx1m6H/2kk9xwycMD6HtHHwA9Yk2jnMUM085lL1W3A2gEn3V73lm99jQuECW8AgYQ3o9J8BpuVuZnH9n5uXjyFPrhc2tCUPDrBes/phFfJycSrGq0Y="
    - REVIEWDOG_VERSION=0.9.11
language: go
go:
  - '1.11.x'

os:
  - linux
  - osx

matrix:
  fast_finish: true
install:
  - go get github.com/wadey/gocovmerge
  - go get golang.org/x/lint/golint
  - mkdir -p ~/bin/ && export export PATH="~/bin/:$PATH"
  - curl -fSL https://github.com/haya14busa/reviewdog/releases/download/${REVIEWDOG_VERSION}/reviewdog_linux_amd64 -o ~/bin/reviewdog && chmod +x ~/bin/reviewdog
before_script:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS
  - ulimit -n 8192
script:
  - >-
    golint ./... | grep -v 'vendor/' | grep -v 'server/' | grep -v 'utils/' | reviewdog -f=golint -reporter=github-pr-review || true

before_deploy:
  - make clean
  - make use_all_cores
  - mkdir -p build
  - tar czvf build/CovenantSQL-$TRAVIS_TAG.$TRAVIS_OS_NAME-amd64.tar.gz $(ls bin/cql* | grep -v test)

deploy:
  provider: releases
  api_key:
    secure: Iyzoj1/OLH1YkmDLpQdn0XBk/pxNIkDVqezVVK3kXRj81FeciAZWFBry2t2140EX6wpMYq9/R4vK0wkMJLvlggXwl4rzWsuz0eahLS8KqjXiEY1up8KBiK0u4GqEV7ZqTcPaNY8aG9s1ptuEXLBbuMZlKFWtLZ4ffoyZv6MIIOT2DkrJeRh1HpIcRfNuS//cqz5PImWtv+lJ9psfTyWMYe4fQ5U+6ewq6KW9qv1jLiuqNmQHW279f7zbZpccMCjOcsZRCYOeAqrcoKrBr2UJc+RyATc1+Iw9JuG9qtc6SObcKzdz/R8ycjFAHdEsGruWWkkE09jnLCHbOPPvPT4DbWzPEsT0dtAtDLtEcPR0rfED/y95iR/6sV5PnjUnzmYg9zrEyC6ryhU8LX6g2r4Ssy8KkIk1kpJVmnilbm4JGT+MLDAyaln1acmkLjMi8EDgIeFt6edOGN4BBu3D7qknUqWk23bn7dkzuXVAKbVDIJOL4zL8K2pBz3uIHgLz6Ebz6WvYjhfjcJP5Gcur6w21Z9jjmM1fdI3/7CHTD/VJtfjyfBvh5oUsb26KBDG97ErDiB0rf8fDiwxGnlgSpdrhvopbIWyCw3ENWdqury8kki7GV9zZw55uHNer33wF+n1KnhhU4oayXk4D/dFGMd7aDl0d+gR90HJljxrWas0/jEc=
  file:
    - build/CovenantSQL-$TRAVIS_TAG.linux-amd64.tar.gz
    - build/CovenantSQL-$TRAVIS_TAG.osx-amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true
